[book]
authors = ["Guan Gui"]
language = "en"
multilingual = false
src = "docs"
title = "Proofable Documentation"

[build]
build-dir = "docs_output/book"

[output.html]
git-repository-url = "https://github.com/SouthbankSoftware/proofable"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = true
exclude = ['https://github.com/SouthbankSoftware/proofable/examples']
command = 'bash -c "ln -s ../../../gh-pages/node_sdk/reference ../html/node_sdk/reference && mdbook-linkcheck"'
