# proofable
# Copyright (C) 2020  Southbank Software Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# @Author: guiguan, koustubhg
# @Date:   2019-01-29T16:05:51+11:00
# @Last modified by:   guiguan
# @Last modified time: 2020-03-10T15:46:46+11:00

version: "3.4"

services:
  tests:
    image: southbanksoftware/proofable-tests:latest
    container_name: tests
    depends_on:
      - api
    command: [
        "/bin/sh",
        "-c",
        "git config --global url.\"https://${GIT_ACCESS_TOKEN}:@github.com/\".insteadOf \"https://github.com/\" \
        && cd /go/proofable \
        && make test-all",
      ]
    environment:
      PROOFABLE_CLI_API_HOST_PORT: "api:10014"
      PROOFABLE_CLI_API_SECURE: "false"
      PROOFABLE_CLI_DEV_TOKEN: "magic"
    volumes:
      - $PWD/proofable:/go/proofable
    networks:
      - backend
  anchor:
    image: provendbdev.azurecr.io/provendb-anchor:latest
    container_name: anchor
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 10008 > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "10008:10008"
      - "11000:11000"
    environment:
      ANCHOR_DISABLE_OPENTRACING: "true"
      ANCHOR_VERIFIER_URI_PREFIX: "http://anchor:11000"
    networks:
      - backend
  api:
    image: provendbdev.azurecr.io/proofable-api:latest
    container_name: api
    depends_on:
      - anchor
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 10014 > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "10014:10014"
    environment:
      API_DISABLE_OPENTRACING: "true"
      API_ANCHOR_HOST_PORT: "anchor:10008"
      API_DEV_TOKEN: "magic"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
