#This task will write to labels/version.json file which will contain verison in the following format
# { "commit": "f31cdba", "semver": "0.0.158"}
---
platform: linux
image_resource:
  type: docker-image
  source: { repository: alpine }
inputs:
  - name: provenx-cli
  - name: version
outputs:
  - name: labels
run:
  path: sh
  args:
    - -exc
    - |
      githash=`cat provenx-cli/.git/short_ref`
      semver=`cat version/number`
      echo "{ \"commit\": \"${githash}\", \"semver\": \"${semver}\"}" > labels/version.json
