# provendb-verify
# Copyright (C) 2019  Southbank Software Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# @Author: guiguan
# @Date:   2019-01-29T16:04:55+11:00
# @Last modified by:   guiguan
# @Last modified time: 2019-02-15T14:13:01+11:00

platform: linux
image_resource:
  type: docker-image
  source: { repository: southbanksoftware/golang-dcind, tag: latest }
inputs:
  - name: version
  - name: proofable-cli
outputs:
  - name: proofable-cli
run:
  path: bash
  args:
    - -exc
    - |
      export APP_VERSION=$(cat version/number)
      cd proofable-cli
      source ci/task-build/dcind.bash
      start_docker
      cleanup() {
        docker stop -t 0 $(docker container ls -a -q) || true
        docker system prune -a -f || true
        stop_docker || true
      }
      trap cleanup EXIT
      await_docker

      make build-all
      mv proofable-cli-darwin-*-amd64 proofable-cli_darwin_amd64
      mv proofable-cli-linux-amd64 proofable-cli_linux_amd64
      mv proofable-cli-windows-*-amd64.exe proofable-cli_windows_amd64.exe
